# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mota < Formula
  desc "A Shelly device firmware updater based on zeroconf (or bonjour) discovery for local networks using their built-in Over-The-Air update interface. It is suited for network setups where IoT devices do not have internet connectivity."
  homepage "https://github.com/ruimarinho/mota"
  version "2.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/ruimarinho/mota/releases/download/v2.1.0/mota_2.1.0_macOS_all.tar.gz"
    sha256 "7860ec4c83554cb8ad8639b9c83615775da4a1b84b2deff964657c1e44840df9"

    def install
      bin.install "mota"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ruimarinho/mota/releases/download/v2.1.0/mota_2.1.0_Linux_x86_64.tar.gz"
      sha256 "bdd10b12794acaee6c57c555a79ee1c74361555a4cefb782c90960918d830a94"

      def install
        bin.install "mota"
      end
    end
  end

  test do
    system "#{bin}/mota --version"
  end
end
