# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShellyUpdater < Formula
  desc "A Shelly device firmware updater based on zeroconf (or bonjour) discovery for local networks using their built-in Over-The-Air update interface. It is suited for network setups where IoT devices do not have internet connectivity."
  homepage "https://github.com/ruimarinho/shelly-updater"
  version "1.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ruimarinho/shelly-updater/releases/download/v1.0.2/shelly-updater_1.0.2_macOS_x86_64.tar.gz"
    sha256 "8ab407e0217c669a86403564682a8cd21e80b34eaff89762b1e158f561b801c9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ruimarinho/shelly-updater/releases/download/v1.0.2/shelly-updater_1.0.2_Linux_x86_64.tar.gz"
    sha256 "fbe649ae5a43e01e877f0be60d31aa84886885f84e7270f5db65c66c34e4b6d8"
  end

  def install
    bin.install "shelly-updater"
  end

  test do
    system "#{bin}/shelly-updater --version"
  end
end
